/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class pl_test_tasklocker_TaskLocker */

#ifndef _Included_pl_test_tasklocker_TaskLocker
#define _Included_pl_test_tasklocker_TaskLocker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_test_tasklocker_TaskLocker
 * Method:    WindowsArch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pl_test_tasklocker_TaskLocker_WindowsArch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
